In [1]:
import pandas as pd

In [2]:
data = {
    "Customer_ID": [
        "C01","C02","C03","C04","C05",
        "C06","C07","C08","C09","C10",
        "C11","C12","C13","C14","C15",
        "C16","C17","C18","C19","C20"
    ],

    "Name": [
        "Aarav Patel","Priya Singh","Rahul Sharma","Ananya Mehta",
        "Vivaan Shah","Isha Verma","Arjun Nair","Diya Joshi",
        "Kabir Kumar","Meera Iyer","Rohan Desai","Sneha Rao",
        "Aditya Gupta","Kavya Reddy","Dev Malhotra","Nisha Jain",
        "Kunal Yadav","Pooja Mishra","Harsh Soni","Riya Kapoor"
    ],

    "Age": [
        22,24,29,31,27,35,26,23,38,30,
        33,25,28,34,21,36,32,27,40,24
    ],

    "Gender": [
        "M","F","M","F","M","F","M","F","M","F",
        "M","F","M","F","M","F","M","F","M","F"
    ],

    "City": [
        "Ahmedabad","Surat","Mumbai","Pune","Rajkot",
        "Delhi","Kochi","Vadodara","Jaipur","Chennai",
        "Gandhinagar","Hyderabad","Noida","Bengaluru",
        "Nashik","Indore","Lucknow","Nagpur","Bhopal","Thane"
    ],

    "Email": [
        "aarav.patel@example.com",
        "priya.singh@example.com",
        "rahul.sharma@example.com",
        "ananya.mehta@example.com",
        "vivaan.shah@example.com",
        "isha.verma@example.com",
        "arjun.nair@example.com",
        "diya.joshi@example.com",
        "kabir.kumar@example.com",
        "meera.iyer@example.com",
        "rohan.desai@example.com",
        "sneha.rao@example.com",
        "aditya.gupta@example.com",
        "kavya.reddy@example.com",
        "dev.malhotra@example.com",
        "nisha.jain@example.com",
        "kunal.yadav@example.com",
        "pooja.mishra@example.com",
        "harsh.soni@example.com",
        "riya.kapoor@example.com"
    ],

    "Purchase_Amount": [
        1850,2400,975,3200,1460,
        4100,2280,760,5400,2890,
        3650,1320,2580,4490,690,
        3780,2140,1690,6200,1180
    ],

    "Payment_Method": [
        "UPI","Credit Card","Cash","UPI","Cash",
        "Credit Card","UPI","Cash","Credit Card","UPI",
        "Credit Card","Cash","UPI","Credit Card","Cash",
        "UPI","Credit Card","UPI","Credit Card","Cash"
    ]
}

df = pd.DataFrame(data)

print("Original Dataset:")
display(df)

Original Dataset:

,Customer_ID,Name,Age,Gender,City,Email,Purchase_Amount,Payment_Method
0,C01,Aarav Patel,22,M,Ahmedabad,aarav.patel@example.com,1850,UPI
1,C02,Priya Singh,24,F,Surat,priya.singh@example.com,2400,Credit Card
2,C03,Rahul Sharma,29,M,Mumbai,rahul.sharma@example.com,975,Cash
3,C04,Ananya Mehta,31,F,Pune,ananya.mehta@example.com,3200,UPI
4,C05,Vivaan Shah,27,M,Rajkot,vivaan.shah@example.com,1460,Cash
5,C06,Isha Verma,35,F,Delhi,isha.verma@example.com,4100,Credit Card
6,C07,Arjun Nair,26,M,Kochi,arjun.nair@example.com,2280,UPI
7,C08,Diya Joshi,23,F,Vadodara,diya.joshi@example.com,760,Cash
8,C09,Kabir Kumar,38,M,Jaipur,kabir.kumar@example.com,5400,Credit Card
9,C10,Meera Iyer,30,F,Chennai,meera.iyer@example.com,2890,UPI
10,C11,Rohan Desai,33,M,Gandhinagar,rohan.desai@example.com,3650,Credit Card
11,C12,Sneha Rao,25,F,Hyderabad,sneha.rao@example.com,1320,Cash
12,C13,Aditya Gupta,28,M,Noida,aditya.gupta@example.com,2580,UPI
13,C14,Kavya Reddy,34,F,Bengaluru,kavya.reddy@example.com,4490,Credit Card
14,C15,Dev Malhotra,21,M,Nashik,dev.malhotra@example.com,690,Cash
15,C16,Nisha Jain,36,F,Indore,nisha.jain@example.com,3780,UPI
16,C17,Kunal Yadav,32,M,Lucknow,kunal.yadav@example.com,2140,Credit Card
17,C18,Pooja Mishra,27,F,Nagpur,pooja.mishra@example.com,1690,UPI
18,C19,Harsh Soni,40,M,Bhopal,harsh.soni@example.com,6200,Credit Card
19,C20,Riya Kapoor,24,F,Thane,riya.kapoor@example.com,1180,Cash

In [3]:
print("Number of records:", len(df))
print("Number of columns:", len(df.columns))

Number of records: 20
Number of columns: 8

In [4]:
personal_columns = [
    "Name",
    "Age",
    "Gender",
    "City",
    "Email"
]

sensitive_columns = [
    "Payment_Method"
]

print("Personal Information:")
print(personal_columns)

print("\nSensitive Information:")
print(sensitive_columns)

Personal Information:
['Name', 'Age', 'Gender', 'City', 'Email']

Sensitive Information:
['Payment_Method']

In [5]:
def mask_email(email):
    first_letter = email[0]
    domain = email[email.index("@"):]
    return first_letter + "***" + domain

df["Masked_Email"] = df["Email"].apply(mask_email)

print(df[["Email", "Masked_Email"]])

                       Email      Masked_Email
0    aarav.patel@example.com  a***@example.com
1    priya.singh@example.com  p***@example.com
2   rahul.sharma@example.com  r***@example.com
3   ananya.mehta@example.com  a***@example.com
4    vivaan.shah@example.com  v***@example.com
5     isha.verma@example.com  i***@example.com
6     arjun.nair@example.com  a***@example.com
7     diya.joshi@example.com  d***@example.com
8    kabir.kumar@example.com  k***@example.com
9     meera.iyer@example.com  m***@example.com
10   rohan.desai@example.com  r***@example.com
11     sneha.rao@example.com  s***@example.com
12  aditya.gupta@example.com  a***@example.com
13   kavya.reddy@example.com  k***@example.com
14  dev.malhotra@example.com  d***@example.com
15    nisha.jain@example.com  n***@example.com
16   kunal.yadav@example.com  k***@example.com
17  pooja.mishra@example.com  p***@example.com
18    harsh.soni@example.com  h***@example.com
19   riya.kapoor@example.com  r***@example.com

In [6]:
def age_group(age):
    if 20 <= age <= 25:
        return "20-25"
    elif 26 <= age <= 30:
        return "26-30"
    elif 31 <= age <= 35:
        return "31-35"
    elif 36 <= age <= 40:
        return "36-40"

df["Age_Group"] = df["Age"].apply(age_group)

print(df[["Age", "Age_Group"]])

    Age Age_Group
0    22     20-25
1    24     20-25
2    29     26-30
3    31     31-35
4    27     26-30
5    35     31-35
6    26     26-30
7    23     20-25
8    38     36-40
9    30     26-30
10   33     31-35
11   25     20-25
12   28     26-30
13   34     31-35
14   21     20-25
15   36     36-40
16   32     31-35
17   27     26-30
18   40     36-40
19   24     20-25

In [7]:
region_map = {
    "Ahmedabad": "Gujarat",
    "Surat": "Gujarat",
    "Rajkot": "Gujarat",
    "Vadodara": "Gujarat",
    "Gandhinagar": "Gujarat",

    "Mumbai": "Maharashtra",
    "Pune": "Maharashtra",
    "Nashik": "Maharashtra",
    "Nagpur": "Maharashtra",
    "Bhopal": "Maharashtra",

    "Delhi": "Other India",
    "Kochi": "Other India",
    "Jaipur": "Other India",
    "Chennai": "Other India",
    "Hyderabad": "Other India",
    "Noida": "Other India",
    "Bengaluru": "Other India",
    "Indore": "Other India",
    "Lucknow": "Other India",
    "Thane": "Other India"
}

df["Region"] = df["City"].map(region_map)

print(df[["City", "Region"]])

           City       Region
0     Ahmedabad      Gujarat
1         Surat      Gujarat
2        Mumbai  Maharashtra
3          Pune  Maharashtra
4        Rajkot      Gujarat
5         Delhi  Other India
6         Kochi  Other India
7      Vadodara      Gujarat
8        Jaipur  Other India
9       Chennai  Other India
10  Gandhinagar      Gujarat
11    Hyderabad  Other India
12        Noida  Other India
13    Bengaluru  Other India
14       Nashik  Maharashtra
15       Indore  Other India
16      Lucknow  Other India
17       Nagpur  Maharashtra
18       Bhopal  Maharashtra
19        Thane  Other India

In [8]:
df["Anonymous_ID"] = [
    f"Customer_{i:03d}"
    for i in range(1, len(df) + 1)
]

print(df[["Name", "Anonymous_ID"]])

            Name  Anonymous_ID
0    Aarav Patel  Customer_001
1    Priya Singh  Customer_002
2   Rahul Sharma  Customer_003
3   Ananya Mehta  Customer_004
4    Vivaan Shah  Customer_005
5     Isha Verma  Customer_006
6     Arjun Nair  Customer_007
7     Diya Joshi  Customer_008
8    Kabir Kumar  Customer_009
9     Meera Iyer  Customer_010
10   Rohan Desai  Customer_011
11     Sneha Rao  Customer_012
12  Aditya Gupta  Customer_013
13   Kavya Reddy  Customer_014
14  Dev Malhotra  Customer_015
15    Nisha Jain  Customer_016
16   Kunal Yadav  Customer_017
17  Pooja Mishra  Customer_018
18    Harsh Soni  Customer_019
19   Riya Kapoor  Customer_020

In [9]:
protected_df = df[
    [
        "Customer_ID",
        "Anonymous_ID",
        "Age_Group",
        "Region",
        "Masked_Email",
        "Purchase_Amount",
        "Payment_Method"
    ]
].copy()

print("Privacy-Preserved Dataset:")
display(protected_df)

Privacy-Preserved Dataset:

,Customer_ID,Anonymous_ID,Age_Group,Region,Masked_Email,Purchase_Amount,Payment_Method
0,C01,Customer_001,20-25,Gujarat,a***@example.com,1850,UPI
1,C02,Customer_002,20-25,Gujarat,p***@example.com,2400,Credit Card
2,C03,Customer_003,26-30,Maharashtra,r***@example.com,975,Cash
3,C04,Customer_004,31-35,Maharashtra,a***@example.com,3200,UPI
4,C05,Customer_005,26-30,Gujarat,v***@example.com,1460,Cash
5,C06,Customer_006,31-35,Other India,i***@example.com,4100,Credit Card
6,C07,Customer_007,26-30,Other India,a***@example.com,2280,UPI
7,C08,Customer_008,20-25,Gujarat,d***@example.com,760,Cash
8,C09,Customer_009,36-40,Other India,k***@example.com,5400,Credit Card
9,C10,Customer_010,26-30,Other India,m***@example.com,2890,UPI
10,C11,Customer_011,31-35,Gujarat,r***@example.com,3650,Credit Card
11,C12,Customer_012,20-25,Other India,s***@example.com,1320,Cash
12,C13,Customer_013,26-30,Other India,a***@example.com,2580,UPI
13,C14,Customer_014,31-35,Other India,k***@example.com,4490,Credit Card
14,C15,Customer_015,20-25,Maharashtra,d***@example.com,690,Cash
15,C16,Customer_016,36-40,Other India,n***@example.com,3780,UPI
16,C17,Customer_017,31-35,Other India,k***@example.com,2140,Credit Card
17,C18,Customer_018,26-30,Maharashtra,p***@example.com,1690,UPI
18,C19,Customer_019,36-40,Maharashtra,h***@example.com,6200,Credit Card
19,C20,Customer_020,20-25,Other India,r***@example.com,1180,Cash

In [10]:
comparison = pd.DataFrame({
    "Original": [
        df.loc[0, "Name"],
        df.loc[0, "Age"],
        df.loc[0, "City"],
        df.loc[0, "Email"]
    ],

    "Protected": [
        df.loc[0, "Anonymous_ID"],
        df.loc[0, "Age_Group"],
        df.loc[0, "Region"],
        df.loc[0, "Masked_Email"]
    ]
})

comparison.index = [
    "Name / ID",
    "Age",
    "City / Region",
    "Email"
]

display(comparison)

                              Original         Protected
Name / ID                  Aarav Patel      Customer_001
Age                                 22             20-25
City / Region                Ahmedabad           Gujarat
Email          aarav.patel@example.com  a***@example.com

In [11]:
age_counts = protected_df["Age_Group"].value_counts().sort_index()

print(age_counts)

Age_Group
20-25    6
26-30    6
31-35    5
36-40    3
Name: count, dtype: int64

In [12]:
region_counts = protected_df["Region"].value_counts()

print(region_counts)

Region
Other India    10
Gujarat         5
Maharashtra     5
Name: count, dtype: int64

In [13]:
payment_counts = protected_df["Payment_Method"].value_counts()

print(payment_counts)

Payment_Method
UPI            7
Credit Card    7
Cash           6
Name: count, dtype: int64

In [14]:
payment_percentage = (
    protected_df["Payment_Method"]
    .value_counts(normalize=True) * 100
)

print(payment_percentage)

Payment_Method
UPI            35.0
Credit Card    35.0
Cash           30.0
Name: proportion, dtype: float64

In [15]:
print("Total Purchase Amount:",
      protected_df["Purchase_Amount"].sum())

print("Average Purchase Amount:",
      protected_df["Purchase_Amount"].mean())

print("Maximum Purchase Amount:",
      protected_df["Purchase_Amount"].max())

print("Minimum Purchase Amount:",
      protected_df["Purchase_Amount"].min())

Total Purchase Amount: 53035
Average Purchase Amount: 2651.75
Maximum Purchase Amount: 6200
Minimum Purchase Amount: 690

In [16]:
print("FINAL ANALYSIS")

print("\n1. Customers by Age Group:")
print(protected_df["Age_Group"].value_counts().sort_index())

print("\n2. Customers by Region:")
print(protected_df["Region"].value_counts())

print("\n3. Payment Method:")
print(protected_df["Payment_Method"].value_counts())

print("\n4. Average Purchase Amount:")
print(protected_df["Purchase_Amount"].mean())

print("\n5. Total Purchase Amount:")
print(protected_df["Purchase_Amount"].sum())

FINAL ANALYSIS

1. Customers by Age Group:
Age_Group
20-25    6
26-30    6
31-35    5
36-40    3
Name: count, dtype: int64

2. Customers by Region:
Region
Other India    10
Gujarat         5
Maharashtra     5
Name: count, dtype: int64

3. Payment Method:
Payment_Method
UPI            7
Credit Card    7
Cash           6
Name: count, dtype: int64

4. Average Purchase Amount:
2651.75

5. Total Purchase Amount:
53035